#!/usr/bin/env bash
set -e
set -o pipefail
export PLUGIN_PATH=${PLUGIN_PATH:="/var/lib/dokku/plugins"}
case "$1" in
  receive)
    APP="$2"; IMAGE="app/$APP"
    echo "-----> Building $APP ..."
    cat | dokku build $APP $IMAGE
    echo "-----> Build complete!"
    echo "-----> Releasing $APP ..."
    dokku release $APP $IMAGE
    echo "-----> Release complete!"
    echo "-----> Migrating $APP ..."
    dokku migrate $APP $IMAGE
    echo "-----> Migration complete!"
    echo "-----> Deploying $APP ..."
    dokku deploy $APP $IMAGE
    echo "-----> Deploy complete!"
    echo "-----> Cleaning up ..."
    dokku cleanup
    echo "-----> Cleanup complete!"
    echo "=====> Application deployed:"
    echo "       $(dokku url $APP)"
    echo
    ;;

  build)
    APP="$2"; IMAGE="$3"; CACHE_DIR="$HOME/$APP/cache"
    id=$(cat | docker run -i -a stdin progrium/buildstep /bin/bash -c "mkdir -p /app && tar -xC /app")
    test $(docker wait $id) -eq 0
    docker commit $id $IMAGE > /dev/null
    [[ -d $CACHE_DIR ]] || mkdir $CACHE_DIR
    pluginhook pre-build $APP $IMAGE
    id=$(docker run -d -v $CACHE_DIR:/cache $IMAGE /build/builder)
    docker attach $id
    test $(docker wait $id) -eq 0
    docker commit $id $IMAGE > /dev/null
    ;;

  release)
    APP="$2"; IMAGE="$3"
    pluginhook pre-release $APP $IMAGE
    if [[ -f "$HOME/$APP/ENV" ]]; then
      id=$(cat "$HOME/$APP/ENV" | docker run -i -a stdin $IMAGE /bin/bash -c "mkdir -p /app/.profile.d && cat > /app/.profile.d/app-env.sh")
      test $(docker wait $id) -eq 0
      docker commit $id $IMAGE > /dev/null
    fi
    pluginhook post-release $APP $IMAGE
    ;;

  migrate)
    APP="$2"; IMAGE="$3"
    pluginhook pre-migrate $APP $IMAGE
    PROCTYPE=$(cat "$HOME/$APP/PROCTYPE")
    id=$(docker run -d -p 5000 -e PORT=5000 $IMAGE /bin/bash -c "/start migrate")
    test $(docker wait $id) -eq 0
    ;;

  deploy)
    APP="$2"; IMAGE="$3"
    pluginhook pre-deploy $APP $IMAGE
    [[ ! -f "$HOME/$APP/PROCTYPE" ]] && echo "web" > "$HOME/$APP/PROCTYPE"
    PROCTYPE=$(cat "$HOME/$APP/PROCTYPE")
    if [[ ! -f "$HOME/$APP/PORT" ]]; then
      # First deploy
      id=$(docker run -d -p 5000 -e PORT=5000 $IMAGE /bin/bash -c "/start $PROCTYPE")
      echo $id > "$HOME/$APP/CONTAINER"
      port=$(docker port $id 5000 | sed -e 's/^.*://')
      echo $port > "$HOME/$APP/PORT"
      echo "http://$(< "$HOME/HOSTNAME"):$port" > "$HOME/$APP/URL"
      oldid=""
    else
      # Regular deploy
      oldid=$(< "$HOME/$APP/CONTAINER")
      
      port=$(< "$HOME/$APP/PORT")
      id=$(docker run -d -p "5000" -e "PORT=5000" $IMAGE /bin/bash -c "/start $PROCTYPE")
      port=$(docker port $id 5000 | sed -e 's/^.*://')
      echo $port > "$HOME/$APP/PORT"
      echo $id > "$HOME/$APP/CONTAINER"
      echo "http://$(< "$HOME/HOSTNAME"):$port" > "$HOME/$APP/URL"
    fi
    pluginhook post-deploy $APP $port

    if [[ -n $oldid ]]; then
      if [[ "$PROCTYPE" = 'web' ]]; then
        sleep 15
      fi
      
      docker stop -t=15 $oldid > /dev/null
    fi
    ;;

  cleanup)
    # delete all non-running container
    docker ps -a | grep 'Exit' |  awk '{print $1}' | xargs docker rm &> /dev/null &
    # delete unused images
    docker images | grep '<none>' |  awk '{print $3}'  | xargs docker rmi &> /dev/null &
    ;;

  plugins)
    ls -1 -d $PLUGIN_PATH/*/
    ;;

  plugins-install)
    pluginhook install
    ;;

  # temporary hack for https://github.com/progrium/dokku/issues/82
  deploy:all)
    for app in $(ls -d $HOME/*/); do
      APP=$(basename $app);
      IMAGE="app/$APP"
      dokku deploy $APP $IMAGE
    done
    ;;

  help)
    cat<<EOF | pluginhook commands help | sort
    help            Print the list of commands
    plugins         Print active plugins
    plugins-install Install active plugins
EOF
    ;;

  *)
    pluginhook commands "$@"
    ;;

esac
