#!/bin/bash
set -e; case "$1" in
  delete)
    if [[ -z $2 ]]; then
        echo "Please specify an app to delete"
        exit 1
    fi
    APP="$2"; IMAGE="app/$APP";
    if [[ ! -d "/home/git/$APP" ]]; then
        echo "App does not exist"
        exit 1
    fi

    pluginhook pre-delete $APP
    ID=$(< "/home/git/$APP/CONTAINER")

    docker stop $ID > /dev/null
    docker images | grep $IMAGE | awk '{print $3}' | xargs docker rmi &> /dev/null &
    docker rm $ID  > /dev/null

    pluginhook post-delete $APP
    ;;

  logs)
    CONTAINER=$(</home/git/$2/CONTAINER)
    docker logs $CONTAINER | tail -n 100
    ;;

  run)
    if [[ -z $2 ]]; then
        echo "Please specify an app to run the command on"
        exit 1
    fi
    APP="$2"; IMAGE="app/$APP"
    if [[ ! -d "/home/git/$APP" ]]; then
        echo "App $APP does not exist"
        exit 1
    fi
    shift 2
    docker run -i -t $IMAGE /exec "$@"
    ;;

  url)
    APP="$2";
    if [[ ! -d "/home/git/$APP" ]]; then
        echo "App $APP does not exist"
        exit 1
    fi

    if [[ -f "/home/git/$APP/URL" ]]; then
      echo $(< "/home/git/$APP/URL")
    fi
    ;;

  proc_type)
    APP="$2";
    if [[ ! -d "/home/git/$APP" ]]; then
        echo "App $APP does not exist"
        exit 1
    fi

    [[ ! -f "/home/git/$APP/PROCTYPE" ]] && echo "web" > "/home/git/$APP/PROCTYPE"
    if [[ -f "/home/git/$APP/PROCTYPE" ]]; then
      echo $(< "/home/git/$APP/PROCTYPE")
    fi
    ;;

  proc_type:set)
    APP="$2"; PROCTYPE="$3";
    if [[ ! -d "/home/git/$APP" ]]; then
        echo "App $APP does not exist"
        exit 1
    fi

    echo $PROCTYPE > "/home/git/$APP/PROCTYPE"
    echo "Procfile will run $PROCTYPE"

    ;;

  help)
    cat && cat<<EOF
    delete <app>                                    Delete an application
    logs <app>                                      Show the last logs for an application
    run <app> <cmd>                                 Run a command in the environment of an application
    url <app>                                       Show the URL for an application
    proc_type <app>                                 Show the command type to execute from Procfile
    proc_type:set <app> <type>                      Sets the type of command to run from Procfile
EOF
    ;;

esac
cat
